using System.Reflection;
using System.Text.Json;

#if  ANDROID
using Android.App;
using Android.Content;
using AndroidX.Core.App;
#endif


namespace catSpin;
using System;
using Microsoft.Maui.Controls;
using Microsoft.Maui.ApplicationModel;
using System.Text.Json;
[Serializable]
public class other
{
    public string words = " words :3";

    public void change_words(Label label)
    {
        label.Text = "new words :3";
    }


    public void create_notirfactions(string title, string message)
    {
        //dev note IDK what I was doing here. prob following a YT tutorial
#if ANDROID
        

        var channel1id="my_channel_1";
        var channelName=" General Notifications";
        var importance = NotificationImportance.High;
        
        var channel = new NotificationChannel(channel1id,channelName,importance);
        var noticationmang= (NotificationManager)Android.App.Application.Context.GetSystemService(Context.NotificationService);
        noticationmang.CreateNotificationChannel(channel);
        
        // builder
        var builder = new NotificationCompat.Builder(Android.App.Application.Context, channel1id)
            //title
            .SetContentTitle(title)
            //text in the notification
            .SetContentText(message)
            //icon idk how big it is suppost to be but rn its the wrong size cuz lazy :3
            .SetSmallIcon(Resource.Drawable.posticon)
            // auto cancel duh
            .SetAutoCancel(true)
            //idk lights or somting, it never worked
            .SetLights(10, 1000, 1000);
        
        
        // send it to user
        var notification = builder.Build();
        var notiMangCompat = NotificationManagerCompat.From(Android.App.Application.Context);
        notiMangCompat.Notify(1,notification);
#endif
    }
    public void create_notirfactions_with_vibration(string title, string message,int duration)
    {
#if ANDROID
        

        var channel1id="my_channel_1";
        var channelName=" General Notifications";
        var importance = NotificationImportance.High;
        
        var channel = new NotificationChannel(channel1id,channelName,importance);
        var noticationmang= (NotificationManager)Android.App.Application.Context.GetSystemService(Context.NotificationService);
        noticationmang.CreateNotificationChannel(channel);
        
        // builder
        var builder = new NotificationCompat.Builder(Android.App.Application.Context, channel1id)
            //title
            .SetContentTitle(title)
            //text in the notification
            .SetContentText(message)
            //icon idk how big it is suppost to be but rn its the wrong size cuz lazy :3
            .SetSmallIcon(Resource.Drawable.posticon)
            // auto cancel duh
            .SetAutoCancel(true)
            //idk lights or somting, it never worked
            .SetLights(10, 1000, 1000);
        
        
        // send it to user
        var notification = builder.Build();
        var notiMangCompat = NotificationManagerCompat.From(Android.App.Application.Context);
        notiMangCompat.Notify(1,notification);
        // About to add vibrations MANUALLY 
        vibrate_phone_Custom_length(duration);
#endif
    }
    
   public async void ask_for_notifaction()
   {
       var status = await Permissions.CheckStatusAsync<Permissions.PostNotifications>();
       if (status != PermissionStatus.Granted)
       {
           await Permissions.RequestAsync<Permissions.PostNotifications>();
       }
       if (status == PermissionStatus.Granted)
       {
           return;
       }
   }

   public void vibrate_phone_Custom_length(int duration)
   {
       var vibrate = Vibration.Default;
       vibrate.Vibrate(duration);
   }
   public async void vibrate_phone_500()
   {
       var vibrate = Vibration.Default;
       vibrate.Vibrate(500);
   }
   public async void vibrate_phone_songish()
   {
       var vibrate = Vibration.Default;
       vibrate.Vibrate(500);
       await Task.Delay(800);
       vibrate.Vibrate(500);
       await Task.Delay(800);
       vibrate.Vibrate(1000);
   }

   public async void OpenLink(String URL,Page page)
   {
       try
       {
           Uri uri = new Uri(URL);
           await Browser.Default.OpenAsync(uri, BrowserLaunchMode.SystemPreferred);
       }
       catch (Exception e)
       {
           page.DisplayAlert("Error", e.Message, "OK");
       }
   }

   public void PlayVideo(string BroIdkHowToDoThis)
   {
       Console.WriteLine("Bro idk How to do this. Ill figure it out later");
   }

    }

    /* permissons that don't need to be asked for ( generated by chatgpt so take it with a grain of salt)
     put after <uses-permission android:name="android.permisson.
     example <uses-permission android:name="android.permisson.BLUETOOTH"/>
ACCESS_NETWORK_STATE
ACCESS_WIFI_STATE
BLUETOOTH
BLUETOOTH_ADMIN
BLUETOOTH_CONNECT
BLUETOOTH_SCAN
BLUETOOTH_ADVERTISE
CHANGE_NETWORK_STATE
CHANGE_WIFI_STATE
CHANGE_WIFI_MULTICAST_STATE
FOREGROUND_SERVICE
INTERNET
MANAGE_OWN_CALLS
MODIFY_AUDIO_SETTINGS
NFC
NEARBY_WIFI_DEVICES
READ_BASIC_PHONE_STATE
READ_SYNC_SETTINGS
READ_SYNC_STATS
RECEIVE_BOOT_COMPLETED
REORDER_TASKS
REQUEST_DELETE_PACKAGES
SET_ALARM
SET_WALLPAPER
SET_WALLPAPER_HINTS
TRANSMIT_IR
USE_BIOMETRIC
VIBRATE
WAKE_LOCK
WRITE_SYNC_SETTINGS


ones that you need to ask for (also generated by chatgpt)

POST_NOTIFICATIONS  

READ_EXTERNAL_STORAGE
WRITE_EXTERNAL_STORAGE
MANAGE_EXTERNAL_STORAGE

CAMERA
RECORD_AUDIO

ACCESS_COARSE_LOCATION
ACCESS_FINE_LOCATION
ACCESS_BACKGROUND_LOCATION

READ_CONTACTS
WRITE_CONTACTS
GET_ACCOUNTS

CALL_PHONE
READ_PHONE_STATE
READ_CALL_LOG
WRITE_CALL_LOG
ANSWER_PHONE_CALLS
ADD_VOICEMAIL
USE_SIP
PROCESS_OUTGOING_CALLS

SEND_SMS
RECEIVE_SMS
READ_SMS
RECEIVE_WAP_PUSH
RECEIVE_MMS

READ_CALENDAR
WRITE_CALENDAR

BODY_SENSORS
BODY_SENSORS_BACKGROUND
*/
    





